site_name: My Machine LED kšiltovka
site_description: Dokumentace k projektu MyMachine - LED kšiltovka

repo_name: BrnoMarsRover/myMachine-LED-cap
repo_url: https://github.com/BrnoMarsRover/myMachine-LED-cap
edit_uri: edit/main/docs/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Big Picture: big_picture.md
  - Konstrukce:
      - Komponenty: construction/komponenty.md
      - Návody: construction/navody.md
  - Hardware:
      - Pinout: hardware/pinout.md
      - Main board:
            - Popis: hardware/main_board/main_board.md
            - BOM: hardware/main_board/bom.md
      - Top board:
            - Popis: hardware/top_board/top_board.md
            - BOM: hardware/top_board/bom.md    
  - Software:
      - Motivace: software/example.md