site_name: My Machine LED kšiltovka
site_description: Dokumentace k projektu MyMachine - LED kšiltovka

repo_name: BrnoMarsRover/myMachine-LED-cap
repo_url: https://github.com/BrnoMarsRover/myMachine-LED-cap
edit_uri: edit/main/docs/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Hardware:
      - Komponenty: hardware/komponenty.md
      - Pinout: hardware/pinout.md
      - Návody: hardware/navody.md
  - Software:
      - Motivace: software/example.md