site_name: My Machine LED kšiltovka
site_description: Dokumentace k projektu MyMachine - LED kšiltovka
repo_name: BrnoMarsRover/myMachine-LED-cap
repo_url: https://github.com/BrnoMarsRover/myMachine-LED-cap.git

theme: readthedocs

nav:
  - Home: index.md
  - Logbook:
      - Week 1: log/page1.md
  - Source: source.md
